version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:80"  # Mapeia a porta 8000 do host para a porta 80 do contêiner
    volumes:
      - ./app:/code/app  # Mapeia o diretório local para o diretório do contêiner
